version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ktea
    binary: ktea
    main: cmd/ktea/main.go
    env:
      - CGO_ENABLED=0
    tags: prd
    goos:
      # - darwin
      - linux
      - windows
    goarch:
      # - arm64
      # - arm
      - amd64

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
