Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 12
Set Width 1200
Set Height 600
Set Padding 5

# Type a command in the terminal.
Type "ktea"
Enter

Wait+Screen /Topics/
Sleep 2s

# search
Type "/"
Type "shipping"
Sleep 0.5s
Enter

# open consumption page
Sleep 2s
Enter
Sleep 0.2s
Enter
Sleep 0.2s
Enter
Sleep 0.2s
Enter
Sleep 2.0s

# view record
Enter
Sleep 1s

# switch to headers
Right
Sleep 0.5s
Down
Sleep 0.5s
Down

Sleep 5s